version: '2'
services:
  registry-cache:
    image: registry-cache
    container_name: registry-cache
    depends_on:
      - redis
      - registry
    volumes:
      - ./thurk:/opt/app
    ports:
      - "3049:3049"
  registry:
    image: registry:2
    restart: always
    container_name: registry
    ports:
      - "5000:5000"
    volumes:
      - ./registry-config.yml:/etc/docker/registry/config.yml
      - ./registry-volume:/var/lib/registry
  redis:
    image: redis
    container_name: registry-redis
    command: redis-server --appendonly yes
    volumes:
      - ./redis-data:/data
