FROM mhart/alpine-node:5.12

ENV NPM_CONFIG_LOGLEVEL info

RUN apk update && apk add git \
    && npm install "gulpjs/gulp.git#4.0" -g

# COPY . /opt/app/

# RUN cp /opt/app/package.json /tmp/package.json \
#     && cd /tmp && npm install \
#     && cp -a /tmp/node_modules /opt/app/

VOLUME ["/opt/app"]
WORKDIR /opt/app

# RUN npm install

EXPOSE 3049

ENTRYPOINT ["bin/entrypoint.sh"]
