FROM mhart/alpine-node:5.12

ENV NPM_CONFIG_LOGLEVEL info

RUN apk update && apk add git \
    && npm install "gulpjs/gulp.git#4.0" -g

COPY ./thurk /opt/app/

RUN cp /opt/app/package.json /tmp/package.json \
    && cd /tmp && npm install \
    && cp -a /tmp/node_modules /opt/app/

WORKDIR /opt/app
RUN gulp buildServer
    && gulp buildClient

EXPOSE 3049

ENTRYPOINT ["node", "./server/dreadache.js"]
